config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :addresses
  resources :sessions,  only: [:index, :new, :create]
  get '/sessions/destroy', to: 'sessions#destroy', as: 'destroy_session'

  root 'addresses#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
	
	before_create :generate_hash

	def generate_hash
	  self.mask = SecureRandom.hex(4)
	end

	def email
		"#{self.mask}@mailed.cf"
	end

  def to_param
    mask
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  def remember_me
    (super == nil) ? '1' : super
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  skip_before_filter  :verify_authenticity_token, only: [:create]

  def index
    @addresses = current_user.addresses
  end

  def show
  end

  def new
    @address = Address.new
  end

  def edit
  end

  def create
    respond_to do |format|
      @address = current_user.addresses.build(address_params)
      if @address.save
        format.html { redirect_to root_path }
        format.json { render :create, status: :ok, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @address.update(address_params)
      redirect_to root_path, notice: 'Address was successfully updated.'
    end
  end

  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find_by!(mask: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params[:address].permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    if (token = params[:token]).blank?
      redirect_to new_session_path 
    else
      user = User.find_by(encrypted_token: token)
      if user
        sign_in(user)
        redirect_to root_path, params.except(:token, :action, :controller)
      else
        redirect_to new_session_path
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_or_initialize_by(email: email)
    if @user.save
      @user.new_token!
      url = url_for controller: :sessions, token: @user.encrypted_token
      UserTokenMailer.login_email(@user, url).deliver_now
      u, @domain, @tld = email.match(/([a-zA-Z0-9._%+-]+)@([a-zA-Z0-9.-]+).(.[a-zA-Z]{2,4})/).captures
      @host = "#{@domain}.#{@tld}"
    else
      render :new
    end
  end

  def destroy
    sign_out()
    redirect_to(new_session_path)
  end

  private

  def email 
    new_session_params[:email]
  end

  def new_session_params
    params.permit(:email)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/addresses/_form.html.haml
= form_for(@address) do |f|
  - if @address.errors.any?
    #error_explanation
      %h2
        = pluralize(@address.errors.count, "error")
        prohibited this address from being saved:
      %ul
        - @address.errors.full_messages.each do |message|
          %li= message
  = f.label :name
  \:
  \#{f.text_field :name}
  %br/
  .actions
    = f.submit

app/views/addresses/edit.html.haml
%h1 Editing Address
= render 'form'
= link_to 'Show', @address
|
\#{link_to 'Back', addresses_path}

app/views/addresses/index.html.haml
%p#notice= notice
%h1 Listing Addresses
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @addresses.each do |address|
      %tr
        %td= address.name
        %td= mail_to address.email, address.email
        %td= link_to 'Edit', edit_address_path(address)
        %td= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Address', new_address_path

app/views/addresses/new.html.haml
%h1 New Address
= render 'form'
= link_to 'Back', addresses_path

app/views/addresses/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_address_path(@address)
|
\#{link_to 'Back', addresses_path}

app/views/home/index.haml
Welcome to mailed.tk!

app/views/layouts/application.haml
!!!
%html
	%head
		%title Mailed
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
%body
- if current_user
	= link_to "Sign Out", destroy_user_session_path, :method => :delete

	%p.notice= notice
	%p.alert= alert

= yield

app/views/layouts/application.html.haml
!!!
%html 
  %head
    %title Mailed
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body

  - if @current_user
    = link_to "log out", destroy_user_session_path, method: 'delete'

= yield